# Form implementation generated from reading ui file 'PhotoOrganizer_v3\mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageSorter(object):
    def setupUi(self, ImageSorter):
        ImageSorter.setObjectName("ImageSorter")
        ImageSorter.resize(600, 300)
        self.mainLayout = QtWidgets.QVBoxLayout(ImageSorter)
        self.mainLayout.setObjectName("mainLayout")
        self.sourceLayout = QtWidgets.QHBoxLayout()
        self.sourceLayout.setObjectName("sourceLayout")
        self.labelSource = QtWidgets.QLabel(parent=ImageSorter)
        self.labelSource.setMinimumWidth(120)
        self.labelSource.setObjectName("labelSource")
        self.sourceLayout.addWidget(self.labelSource)
        self.lineEditSource = QtWidgets.QLineEdit(parent=ImageSorter)
        self.lineEditSource.setObjectName("lineEditSource")
        self.sourceLayout.addWidget(self.lineEditSource)
        self.btnBrowseSource = QtWidgets.QPushButton(parent=ImageSorter)
        self.btnBrowseSource.setObjectName("btnBrowseSource")
        self.sourceLayout.addWidget(self.btnBrowseSource)
        self.mainLayout.addLayout(self.sourceLayout)
        self.destinationLayout = QtWidgets.QHBoxLayout()
        self.destinationLayout.setObjectName("destinationLayout")
        self.labelDestination = QtWidgets.QLabel(parent=ImageSorter)
        self.labelDestination.setMinimumWidth(120)
        self.labelDestination.setObjectName("labelDestination")
        self.destinationLayout.addWidget(self.labelDestination)
        self.lineEditDestination = QtWidgets.QLineEdit(parent=ImageSorter)
        self.lineEditDestination.setObjectName("lineEditDestination")
        self.destinationLayout.addWidget(self.lineEditDestination)
        self.btnBrowseDestination = QtWidgets.QPushButton(parent=ImageSorter)
        self.btnBrowseDestination.setObjectName("btnBrowseDestination")
        self.destinationLayout.addWidget(self.btnBrowseDestination)
        self.mainLayout.addLayout(self.destinationLayout)
        self.groupBoxOptions = QtWidgets.QGroupBox(parent=ImageSorter)
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.groupBoxOptions)
        self.optionsLayout.setObjectName("optionsLayout")
        self.checkBoxSortByDay = QtWidgets.QCheckBox(parent=self.groupBoxOptions)
        self.checkBoxSortByDay.setObjectName("checkBoxSortByDay")
        self.optionsLayout.addWidget(self.checkBoxSortByDay)
        self.checkBoxRemoveEmpty = QtWidgets.QCheckBox(parent=self.groupBoxOptions)
        self.checkBoxRemoveEmpty.setObjectName("checkBoxRemoveEmpty")
        self.optionsLayout.addWidget(self.checkBoxRemoveEmpty)
        self.mainLayout.addWidget(self.groupBoxOptions)
        self.btnStart = QtWidgets.QPushButton(parent=ImageSorter)
        self.btnStart.setMinimumHeight(40)
        self.btnStart.setStyleSheet("\n"
"       QPushButton {\n"
"           background-color: #4CAF50;\n"
"           color: white;\n"
"           font-weight: bold;\n"
"           border-radius: 6px;\n"
"       }\n"
"       QPushButton:hover {\n"
"           background-color: #45A049;\n"
"       }\n"
"      ")
        self.btnStart.setObjectName("btnStart")
        self.mainLayout.addWidget(self.btnStart)

        self.retranslateUi(ImageSorter)
        QtCore.QMetaObject.connectSlotsByName(ImageSorter)

    def retranslateUi(self, ImageSorter):
        _translate = QtCore.QCoreApplication.translate
        ImageSorter.setWindowTitle(_translate("ImageSorter", "Image Sorting Tool"))
        self.labelSource.setText(_translate("ImageSorter", "📂 Source Folder:"))
        self.btnBrowseSource.setText(_translate("ImageSorter", "Browse…"))
        self.labelDestination.setText(_translate("ImageSorter", "📁 Destination Folder:"))
        self.btnBrowseDestination.setText(_translate("ImageSorter", "Browse…"))
        self.groupBoxOptions.setTitle(_translate("ImageSorter", "Sorting Options"))
        self.checkBoxSortByDay.setText(_translate("ImageSorter", "📅 Sort into subfolders by day"))
        self.checkBoxRemoveEmpty.setText(_translate("ImageSorter", "🗑️ Remove empty folders after sorting"))
        self.btnStart.setText(_translate("ImageSorter", "🚀 Start Sorting"))
