# Form implementation generated from reading ui file 'PhotoOrganizer_v3\progressWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProgressWindow(object):
    def setupUi(self, ProgressWindow):
        ProgressWindow.setObjectName("ProgressWindow")
        ProgressWindow.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(parent=ProgressWindow)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.labelSorted = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelSorted.setObjectName("labelSorted")
        self.statsLayout.addWidget(self.labelSorted)
        self.labelRemaining = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelRemaining.setObjectName("labelRemaining")
        self.statsLayout.addWidget(self.labelRemaining)
        self.verticalLayout.addLayout(self.statsLayout)
        self.groupBoxLogs = QtWidgets.QGroupBox(parent=ProgressWindow)
        self.groupBoxLogs.setObjectName("groupBoxLogs")
        self.logLayout = QtWidgets.QVBoxLayout(self.groupBoxLogs)
        self.logLayout.setObjectName("logLayout")
        self.plainTextEditLogs = QtWidgets.QPlainTextEdit(parent=self.groupBoxLogs)
        self.plainTextEditLogs.setReadOnly(True)
        self.plainTextEditLogs.setStyleSheet("\n"
"          QPlainTextEdit {\n"
"              background-color: #f9f9f9;\n"
"              border: 1px solid #ccc;\n"
"              font-family: Consolas;\n"
"          }\n"
"         ")
        self.plainTextEditLogs.setObjectName("plainTextEditLogs")
        self.logLayout.addWidget(self.plainTextEditLogs)
        self.verticalLayout.addWidget(self.groupBoxLogs)

        self.retranslateUi(ProgressWindow)
        QtCore.QMetaObject.connectSlotsByName(ProgressWindow)

    def retranslateUi(self, ProgressWindow):
        _translate = QtCore.QCoreApplication.translate
        ProgressWindow.setWindowTitle(_translate("ProgressWindow", "Sorting Progress"))
        self.progressBar.setFormat(_translate("ProgressWindow", "%p% - 0 files/sec"))
        self.labelSorted.setText(_translate("ProgressWindow", "✅ Sorted: 0"))
        self.labelRemaining.setText(_translate("ProgressWindow", "⌛ Remaining: 0"))
        self.groupBoxLogs.setTitle(_translate("ProgressWindow", "📝 Log Output"))
