# Form implementation generated from reading ui file 'assets/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 315)
        MainWindow.setMinimumSize(QtCore.QSize(600, 315))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 315))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_source = QtWidgets.QGridLayout()
        self.gridLayout_source.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_source.setObjectName("gridLayout_source")
        self.btnBrowseSource = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBrowseSource.setMinimumSize(QtCore.QSize(90, 30))
        self.btnBrowseSource.setMaximumSize(QtCore.QSize(100, 30))
        self.btnBrowseSource.setObjectName("btnBrowseSource")
        self.gridLayout_source.addWidget(self.btnBrowseSource, 1, 2, 1, 1)
        self.lineEditSource = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditSource.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEditSource.setObjectName("lineEditSource")
        self.gridLayout_source.addWidget(self.lineEditSource, 1, 0, 1, 2)
        self.labelSource = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelSource.setObjectName("labelSource")
        self.gridLayout_source.addWidget(self.labelSource, 0, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_source)
        self.gridLayout_Destination = QtWidgets.QGridLayout()
        self.gridLayout_Destination.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Destination.setObjectName("gridLayout_Destination")
        self.btnBrowseDestination = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnBrowseDestination.setMinimumSize(QtCore.QSize(90, 30))
        self.btnBrowseDestination.setMaximumSize(QtCore.QSize(100, 30))
        self.btnBrowseDestination.setObjectName("btnBrowseDestination")
        self.gridLayout_Destination.addWidget(self.btnBrowseDestination, 1, 2, 1, 1)
        self.lineEditDestination = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditDestination.setMaximumSize(QtCore.QSize(16777215, 26))
        self.lineEditDestination.setObjectName("lineEditDestination")
        self.gridLayout_Destination.addWidget(self.lineEditDestination, 1, 0, 1, 2)
        self.labelDestination = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelDestination.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelDestination.setObjectName("labelDestination")
        self.gridLayout_Destination.addWidget(self.labelDestination, 0, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_Destination)
        self.groupBoxOptions = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxOptions.setMinimumSize(QtCore.QSize(578, 99))
        self.groupBoxOptions.setMaximumSize(QtCore.QSize(16777215, 99))
        self.groupBoxOptions.setCheckable(False)
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.optionsLayout = QtWidgets.QVBoxLayout(self.groupBoxOptions)
        self.optionsLayout.setObjectName("optionsLayout")
        self.checkBoxSortByDay = QtWidgets.QCheckBox(parent=self.groupBoxOptions)
        self.checkBoxSortByDay.setMaximumSize(QtCore.QSize(16777215, 24))
        self.checkBoxSortByDay.setObjectName("checkBoxSortByDay")
        self.optionsLayout.addWidget(self.checkBoxSortByDay)
        self.checkBoxRemoveEmpty = QtWidgets.QCheckBox(parent=self.groupBoxOptions)
        self.checkBoxRemoveEmpty.setObjectName("checkBoxRemoveEmpty")
        self.optionsLayout.addWidget(self.checkBoxRemoveEmpty)
        self.verticalLayout.addWidget(self.groupBoxOptions)
        self.btnStartSorting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnStartSorting.setEnabled(True)
        self.btnStartSorting.setMinimumSize(QtCore.QSize(25, 40))
        self.btnStartSorting.setStyleSheet("\n"
"       QPushButton {\n"
"           background-color: #4CAF50;\n"
"           color: white;\n"
"           font-weight: bold;\n"
"           border-radius: 4px;\n"
"       }\n"
"       QPushButton:hover {\n"
"           background-color: #45A049;\n"
"       }\n"
"      ")
        self.btnStartSorting.setObjectName("btnStartSorting")
        self.verticalLayout.addWidget(self.btnStartSorting)
        MainWindow.setCentralWidget(self.centralwidget)
        self.labelSource.setBuddy(self.btnBrowseSource)
        self.labelDestination.setBuddy(self.btnBrowseDestination)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btnBrowseSource, self.btnBrowseDestination)
        MainWindow.setTabOrder(self.btnBrowseDestination, self.checkBoxSortByDay)
        MainWindow.setTabOrder(self.checkBoxSortByDay, self.checkBoxRemoveEmpty)
        MainWindow.setTabOrder(self.checkBoxRemoveEmpty, self.btnStartSorting)
        MainWindow.setTabOrder(self.btnStartSorting, self.lineEditSource)
        MainWindow.setTabOrder(self.lineEditSource, self.lineEditDestination)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Photo Organizer v3.0"))
        self.btnBrowseSource.setText(_translate("MainWindow", "Browse…"))
        self.labelSource.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">📂</span> Source Folder:</p></body></html>"))
        self.btnBrowseDestination.setText(_translate("MainWindow", "Browse…"))
        self.labelDestination.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">📁</span> Destination Folder:</p></body></html>"))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Sorting Options"))
        self.checkBoxSortByDay.setText(_translate("MainWindow", "📅 Sort into subfolders by day"))
        self.checkBoxRemoveEmpty.setText(_translate("MainWindow", "🗑️ Remove empty folders after sorting"))
        self.btnStartSorting.setText(_translate("MainWindow", "🚀 Start Sorting"))
