# Form implementation generated from reading ui file 'src\assets\ProgressWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProgressWindow(object):
    def setupUi(self, ProgressWindow):
        ProgressWindow.setObjectName("ProgressWindow")
        ProgressWindow.resize(500, 300)
        ProgressWindow.setMinimumSize(QtCore.QSize(500, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgressWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressBar = QtWidgets.QProgressBar(parent=ProgressWindow)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 8))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 8))
        self.progressBar.setTextVisible(False)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: none;\n"
"    background: #dcdcdc;\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #0078d7;\n"
"    border-radius: 4px;\n"
"}")
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.labelPercentage = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelPercentage.setMinimumSize(QtCore.QSize(40, 0))
        self.labelPercentage.setMaximumSize(QtCore.QSize(40, 16777215))
        self.labelPercentage.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelPercentage.setObjectName("labelPercentage")
        self.progressLayout.addWidget(self.labelPercentage)
        self.verticalLayout.addLayout(self.progressLayout)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.labelRemaining = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelRemaining.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelRemaining.setObjectName("labelRemaining")
        self.statsLayout.addWidget(self.labelRemaining)
        self.labelSorted = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelSorted.setObjectName("labelSorted")
        self.statsLayout.addWidget(self.labelSorted)
        self.labelFailed = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelFailed.setObjectName("labelFailed")
        self.statsLayout.addWidget(self.labelFailed)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.statsLayout.addItem(spacerItem)
        self.labelTime = QtWidgets.QLabel(parent=ProgressWindow)
        self.labelTime.setObjectName("labelTime")
        self.statsLayout.addWidget(self.labelTime)
        self.verticalLayout.addLayout(self.statsLayout)
        self.groupBoxLogs = QtWidgets.QGroupBox(parent=ProgressWindow)
        self.groupBoxLogs.setObjectName("groupBoxLogs")
        self.logLayout = QtWidgets.QVBoxLayout(self.groupBoxLogs)
        self.logLayout.setObjectName("logLayout")
        self.plainTextEditLogs = QtWidgets.QPlainTextEdit(parent=self.groupBoxLogs)
        self.plainTextEditLogs.setAutoFillBackground(False)
        self.plainTextEditLogs.setStyleSheet("")
        self.plainTextEditLogs.setReadOnly(True)
        self.plainTextEditLogs.setPlainText("")
        self.plainTextEditLogs.setOverwriteMode(False)
        self.plainTextEditLogs.setBackgroundVisible(False)
        self.plainTextEditLogs.setPlaceholderText("")
        self.plainTextEditLogs.setObjectName("plainTextEditLogs")
        self.logLayout.addWidget(self.plainTextEditLogs)
        self.verticalLayout.addWidget(self.groupBoxLogs)
        self.groupBoxLogs.raise_()
        self.progressBar.raise_()

        self.retranslateUi(ProgressWindow)
        QtCore.QMetaObject.connectSlotsByName(ProgressWindow)

    def retranslateUi(self, ProgressWindow):
        _translate = QtCore.QCoreApplication.translate
        ProgressWindow.setWindowTitle(_translate("ProgressWindow", "Sorting Progress"))
        self.labelPercentage.setText(_translate("ProgressWindow", "0%"))
        self.labelRemaining.setText(_translate("ProgressWindow", "🔄️ Remaining: 0"))
        self.labelSorted.setText(_translate("ProgressWindow", "   ✅ Sorted: 0"))
        self.labelFailed.setText(_translate("ProgressWindow", "   ❌ Failed: 0"))
        self.labelTime.setText(_translate("ProgressWindow", "⌛Time remaining: "))
        self.groupBoxLogs.setTitle(_translate("ProgressWindow", "📝 Log Output"))
